import AppImages from "../FSAssets/FSImages";
import FSColors from "./FSColors";

export const FSDummystring = {
    title: 'Fitness',
    begginerTutorialList: [
        {
            title: 'Basic Jump Tutorial',
            bgImage: AppImages.ic_jumpRopes,
            videoUrl: 'https://youtu.be/TxFeUcIPUHs',
        },
        {
            title: 'Alternate Foot Jump Tutorial',
            bgImage: AppImages.ic_footJump,
            videoUrl: 'https://youtu.be/s_nuLdHYmBY',
        },
        {
            title: 'What is Freestyle Jump?',
            bgImage: AppImages.ic_FreeStyleJumpRopes,
            videoUrl: 'https://youtu.be/d2Kq-nqKRrY',
        },
        {
            title: 'Boxer Step Tutorial',
            bgImage: AppImages.ic_boxerStep,
            videoUrl: 'https://youtu.be/qwi-8Td0nh8',
        },
        {
            title: 'Jump Rope Jacks Tutorial',
            bgImage: AppImages.ic_jumpRopeJacks,
            videoUrl: 'https://youtu.be/R3HVpJO_T-A',
        },
        {
            title: 'Criss-Cross Tutorial',
            bgImage: AppImages.ic_footJump,
            videoUrl: 'https://youtu.be/CEcOWZIis7Y',

        },

    ],
    ratingList: [
        {
            image: AppImages.ic_rating
        },
        {
            image: AppImages.ic_rating
        },
        {
            image: AppImages.ic_rating
        },
        {
            image: AppImages.ic_rating
        },
        {
            image: AppImages.ic_rating
        },

    ],

};

export const FSDummyWorkOutData = [
    {
        id: "workOutId1",
        title: "Sweat It Out",
        date: "July 08, 2021",
        time: "11",
        count: '100',
        starRating: 5,
        circleColor: ['black', 'grey', 'white', 'olivedrab'],
        ropeLB: ['2 LB', '1 LB', '1/2 LB', '1/4 LB'],
        category: 'Endurance',
        tag: 'Intermediate',
        equipments: 'Dumbells',
        favourite: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM3ricC8xjhXu1-CFRMrwKHLdPJGRRdiep5A&usqp=CAU",
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "10s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "20s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
        ],
    },
    {
        id: "workOutId2",
        title: "Getting Movement",
        date: "July 9, 2021",
        time: "11",
        count: '100',
        starRating: 3,
        circleColor: ['white', 'olivedrab'],
        ropeLB: ['1/2 LB', '1/4 LB'],
        category: 'Strength',
        tag: 'Beginner',
        equipments: 'Dumbells',
        favourite: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRtzQ3azKsH8Be0Nheo6cyuG5Dd59qXK7tVA&usqp=CAU",
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "25s basic jump",
                        rest_time: "20s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
        ],
    },
    {
        id: "workOutId3",
        title: "Power Style Tabata",
        date: "July 10, 2021",
        time: "11",
        count: '100',
        starRating: 1,
        circleColor: ['black', 'grey'],
        ropeLB: ['2 LB', '1 LB'],
        category: 'Endurance',
        tag: 'Beginner',
        equipments: 'Ropes',
        favourite: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM3ricC8xjhXu1-CFRMrwKHLdPJGRRdiep5A&usqp=CAU",
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "20s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "15s basic jump",
                        rest_time: "20s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
        ],
    },
    {
        id: "workOutId4",
        title: "HIIT High, HIIT Low",
        date: "July 11, 2021",
        time: "11",
        count: '100',
        starRating: 2,
        circleColor: ['white', 'olivedrab'],
        ropeLB: ['1/2 LB', '1/4 LB'],
        category: 'Endurance',
        tag: 'Beginner',
        equipments: 'Ropes',
        favourite: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRtzQ3azKsH8Be0Nheo6cyuG5Dd59qXK7tVA&usqp=CAU",
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "15s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
        ],
    },
    {
        id: "workOutId5",
        title: "Getting Movement",
        date: "July 9, 2021",
        time: "11",
        count: '100',
        starRating: 4,
        circleColor: ['white', 'olivedrab'],
        ropeLB: ['1/2 LB', '1/4 LB'],
        category: 'Strength',
        tag: 'Intermediate',
        equipments: 'Dumbells',
        favourite: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM3ricC8xjhXu1-CFRMrwKHLdPJGRRdiep5A&usqp=CAU",
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "15s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
        ],
    },
    {
        id: "workOutId6",
        title: "Power Style Tabata",
        date: "July 10, 2021",
        time: "11",
        count: '100',
        starRating: 3,
        circleColor: ['black', 'grey'],
        ropeLB: ['2 LB', '1 LB'],
        category: 'Endurance',
        tag: 'Intermediate',
        equipments: 'Ropes',
        favourite: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRtzQ3azKsH8Be0Nheo6cyuG5Dd59qXK7tVA&usqp=CAU",
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
        ],
    },
    {
        id: "workOutId7",
        title: "HIIT High, HIIT Low",
        date: "July 11, 2021",
        time: "11",
        count: '100',
        starRating: 3,
        circleColor: ['white', 'olivedrab'],
        ropeLB: ['1/2 LB', '1/4 LB'],
        category: 'Endurance',
        tag: 'Beginner',
        equipments: 'Dumbells',
        favourite: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM3ricC8xjhXu1-CFRMrwKHLdPJGRRdiep5A&usqp=CAU",
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "25s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
        ],
    },
]

export const FSDummyPagerString = ['This Week', 'This Month', 'This Year', 'All Time']

export const FSDummyWorkoutsData = {
    name: "Workouts",
    value: '0',
    icon: 'https://image.flaticon.com/icons/png/128/2413/2413179.png',
}

export const FSDummyChallengesData = {
    name: "Challenges",
    value: '0',
    icon: 'https://image.flaticon.com/icons/png/128/2413/2413179.png',
}

export const nextDate = [
    '2021-06-28',
    '2021-06-29',
    '2021-07-04',
    '2021-07-06',
    '2021-09-06',
    '2021-08-05',
];

export const FSDummyDaysData = {
    label: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
    calories: [50, 80, 40, 95, 4, 24, 85],
}

export const FSDummyMonthsData = {
    label: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30' ],
    calories: [50, 80, 40, 95, 4, 24, 85, 67, 2, 89, 45, 21, 7, 23, 65, 98, 1, 6, 45, 76, 1, 71, 12, 90, 34, 65, 12, 6, 57, 31, 1],
}

export const FSDummyYearData = {
    label: ['J', 'F', 'M', 'E', 'M', 'J', 'J', 'O', 'S', 'O', 'N', 'D'],
    calories: [50, 80, 40, 95, 4, 24, 85, 67, 2, 89, 45, 21],
}

export const FSDummySetsData = [
    {
        id: "1",
        name: "Get Fit Bundle",
        price: '$100 USD',
        detail: "Fitbit, Inc. is an American consumer electronics and fitness company.",
        url: "https://cdn.shopify.com/s/files/1/0316/7810/3691/products/Crossrope_SlimGreen_Ver3_2020_1_1__00540.1584545422.1280.1280_a36f72cc-df32-4a17-be35-3b359733a4aa.png?v=1588358914",
        link: "https://www.google.com",
    },
    {
        id: "2",
        name: "Crossrope LE Mat",
        price: '$100 USD',
        detail: "Fitbit, Inc. is an American consumer electronics and fitness company.",
        url: "https://cdn.shopify.com/s/files/1/0316/7810/3691/products/Crossrope_SlimGreen_Ver3_2020_1_1__00540.1584545422.1280.1280_a36f72cc-df32-4a17-be35-3b359733a4aa.png?v=1588358914",
        link: "https://www.google.com",
    },
    {
        id: "3",
        name: "Get Fit Bundle",
        price: '$100 USD',
        detail: "Fitbit, Inc. is an American consumer electronics and fitness company.",
        url: "https://cdn.shopify.com/s/files/1/0316/7810/3691/products/Crossrope_SlimGreen_Ver3_2020_1_1__00540.1584545422.1280.1280_a36f72cc-df32-4a17-be35-3b359733a4aa.png?v=1588358914",
        link: "https://www.google.com",
    },
    {
        id: "4",
        name: "Crossrope LE Mat",
        price: '$100 USD',
        detail: "Fitbit, Inc. is an American consumer electronics and fitness company.",
        url: "https://cdn.shopify.com/s/files/1/0316/7810/3691/products/Crossrope_SlimGreen_Ver3_2020_1_1__00540.1584545422.1280.1280_a36f72cc-df32-4a17-be35-3b359733a4aa.png?v=1588358914",
        link: "https://www.google.com",
    },
]

export const FSDummyRopesHandlesData = [
    {
        id: "1",
        name: "Slim Handles",
        price: '$100 USD',
        detail: "Fitbit, Inc. is an American consumer electronics and fitness company.",
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ10pnzpAZW6kHheVn6SaSnS_Kn3ECwIcHRvQ&usqp=CAU",
        link: "https://www.google.com",
    },
    {
        id: "2",
        name: "Power Handles",
        price: '$100 USD',
        detail: "Fitbit, Inc. is an American consumer electronics and fitness company.",
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ10pnzpAZW6kHheVn6SaSnS_Kn3ECwIcHRvQ&usqp=CAU",
        link: "https://www.google.com",
    },
    {
        id: "3",
        name: "Slim Handles",
        price: '$100 USD',
        detail: "Fitbit, Inc. is an American consumer electronics and fitness company.",
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ10pnzpAZW6kHheVn6SaSnS_Kn3ECwIcHRvQ&usqp=CAU",
        link: "https://www.google.com",
    },
    {
        id: "4",
        name: "Power Handles",
        price: '$100 USD',
        detail: "Fitbit, Inc. is an American consumer electronics and fitness company.",
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ10pnzpAZW6kHheVn6SaSnS_Kn3ECwIcHRvQ&usqp=CAU",
        link: "https://www.google.com",
    },
]

export const challengesList = [
    {
        id: "1",
        title: "Have a Blast challenge",
        overview: 'Ready to say goodbye to the boring cardio? Burn calories fast (and have fun doing it) with our 14 days Have a Blast Challenge full of body weight + jump rope workouts designed to keep you motivated from start to finish.',
        premiumText: 'Upgrade to premium to access this challenge after September 7th, 2021, at 5:00 PM EST',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5O9sUwohx3Ap1qzSKo0ok44van0zvORrsHA&usqp=CAU",
        count: "477",
        starRating: 0,
        link: "https://www.google.com",
        circleColor: ['black', 'grey', 'white', 'olivedrab'],
        ropeLB: ['2 LB', '1 LB', '1/2 LB', '1/4 LB'],
        dailyChallenges: [
            {
                id: '0',
                dayCount: 'DAY 1',
                name: 'Have a Blast Challenge',
                minutes: '11',
            },
            {
                id: '1',
                dayCount: 'DAY 2',
                name: 'Have a Blast Challenge',
                minutes: '13',
            },
            {
                id: '2',
                dayCount: 'DAY 3',
                name: 'Have a Blast Challenge',
                minutes: '15',
            },
            {
                id: '3',
                dayCount: 'DAY 4',
                name: 'Have a Blast Challenge',
                minutes: '17',
            },
        ],
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "10s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "20s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
        ],
    },
    {
        id: "2",
        title: "Low Impact Jump Rope Fitness",
        overview: 'Ready to say goodbye to the boring cardio? Burn calories fast (and have fun doing it) with our 14 days Have a Blast Challenge full of body weight + jump rope workouts designed to keep you motivated from start to finish.',
        premiumText: 'Upgrade to premium to access this challenge after September 7th, 2021, at 5:00 PM EST',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRx0ZOeUgBvAtVePHCgKVOzJ0WpXtuHZDUSw&usqp=CAU",
        count: "457",
        starRating: 0,
        link: "https://www.google.com",
        circleColor: ['white', 'olivedrab'],
        ropeLB: ['1/2 LB', '1/4 LB'],
        dailyChallenges: [
            {
                id: '0',
                dayCount: 'DAY 1',
                name: 'Low Impact Jump Rope Fitness',
                minutes: '11',
            },
            {
                id: '1',
                dayCount: 'DAY 2',
                name: 'Low Impact Jump Rope Fitness',
                minutes: '13',
            },
            {
                id: '2',
                dayCount: 'DAY 3',
                name: 'Low Impact Jump Rope Fitness',
                minutes: '15',
            },
            {
                id: '3',
                dayCount: 'DAY 4',
                name: 'Low Impact Jump Rope Fitness',
                minutes: '17',
            },
            {
                id: '4',
                dayCount: 'DAY 5',
                name: 'Low Impact Jump Rope Fitness',
                minutes: '17',
            },
            {
                id: '5',
                dayCount: 'DAY 6',
                name: 'Low Impact Jump Rope Fitness',
                minutes: '15',
            },
            {
                id: '6',
                dayCount: 'DAY 7',
                name: 'Low Impact Jump Rope Fitness',
                minutes: '20',
            },
            {
                id: '7',
                dayCount: 'DAY 7',
                name: 'Low Impact Jump Rope Fitness',
                minutes: '17',
            },
            {
                id: '8',
                dayCount: 'DAY 8',
                name: 'Low Impact Jump Rope Fitness',
                minutes: '17',
            },
            {
                id: '9',
                dayCount: 'DAY 9',
                name: 'Low Impact Jump Rope Fitness',
                minutes: '15',
            },
            {
                id: '10',
                dayCount: 'DAY 10',
                name: 'Low Impact Jump Rope Fitness',
                minutes: '20',
            },
        ],
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "25s basic jump",
                        rest_time: "20s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
        ],
    },
    {
        id: "3",
        title: "Slow & Steady Challenge",
        overview: 'Ready to say goodbye to the boring cardio? Burn calories fast (and have fun doing it) with our 14 days Have a Blast Challenge full of body weight + jump rope workouts designed to keep you motivated from start to finish.',
        premiumText: 'Upgrade to premium to access this challenge after September 7th, 2021, at 5:00 PM EST',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5O9sUwohx3Ap1qzSKo0ok44van0zvORrsHA&usqp=CAU",
        count: "4,577",
        starRating: 0,
        link: "https://www.google.com",
        circleColor: ['black', 'grey'],
        ropeLB: ['2 LB', '1 LB'],
        dailyChallenges: [
            {
                id: '0',
                dayCount: 'DAY 1',
                name: 'Slow & Steady Challenge',
                minutes: '11',
            },
            {
                id: '1',
                dayCount: 'DAY 2',
                name: 'Slow & Steady Challenge',
                minutes: '13',
            },
            {
                id: '2',
                dayCount: 'DAY 3',
                name: 'Slow & Steady Challenge',
                minutes: '15',
            },
            {
                id: '3',
                dayCount: 'DAY 4',
                name: 'Slow & Steady Challenge',
                minutes: '17',
            },
        ],
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "20s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "15s basic jump",
                        rest_time: "20s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
        ],
    },
    {
        id: "4",
        title: "Jump Into Summer Challenge",
        overview: 'Ready to say goodbye to the boring cardio? Burn calories fast (and have fun doing it) with our 14 days Have a Blast Challenge full of body weight + jump rope workouts designed to keep you motivated from start to finish.',
        premiumText: 'Upgrade to premium to access this challenge after September 7th, 2021, at 5:00 PM EST',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRx0ZOeUgBvAtVePHCgKVOzJ0WpXtuHZDUSw&usqp=CAU",
        count: "7,577",
        starRating: 0,
        link: "https://www.google.com",
        circleColor: ['grey', 'white'],
        ropeLB: ['1 LB', '1/2 LB',],
        dailyChallenges: [
            {
                id: '0',
                dayCount: 'DAY 1',
                name: 'Jump Into Summer Challenge',
                minutes: '11',
            },
            {
                id: '1',
                dayCount: 'DAY 2',
                name: 'Jump Into Summer Challenge',
                minutes: '13',
            },
            {
                id: '2',
                dayCount: 'DAY 3',
                name: 'Jump Into Summer Challenge',
                minutes: '15',
            },
            {
                id: '3',
                dayCount: 'DAY 4',
                name: 'Jump Into Summer Challenge',
                minutes: '17',
            },
        ],
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "15s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
        ],
    },
    {
        id: "5",
        title: "Have a Blast challenge",
        overview: 'Ready to say goodbye to the boring cardio? Burn calories fast (and have fun doing it) with our 14 days Have a Blast Challenge full of body weight + jump rope workouts designed to keep you motivated from start to finish.',
        premiumText: 'Upgrade to premium to access this challenge after September 7th, 2021, at 5:00 PM EST',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5O9sUwohx3Ap1qzSKo0ok44van0zvORrsHA&usqp=CAU",
        count: "4,998",
        starRating: 0,
        link: "https://www.google.com",
        circleColor: ['black', 'olivedrab'],
        ropeLB: ['2 LB', '1/4 LB'],
        dailyChallenges: [
            {
                id: '0',
                dayCount: 'DAY 1',
                name: 'Have a Blast Challenge',
                minutes: '11',
            },
            {
                id: '1',
                dayCount: 'DAY 2',
                name: 'Have a Blast Challenge',
                minutes: '13',
            },
            {
                id: '2',
                dayCount: 'DAY 3',
                name: 'Have a Blast Challenge',
                minutes: '15',
            },
            {
                id: '3',
                dayCount: 'DAY 4',
                name: 'Have a Blast Challenge',
                minutes: '17',
            },
        ],
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "15s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
        ],
    },
    {
        id: "6",
        title: "Slow & Steady Challenge",
        overview: 'Ready to say goodbye to the boring cardio? Burn calories fast (and have fun doing it) with our 14 days Have a Blast Challenge full of body weight + jump rope workouts designed to keep you motivated from start to finish.',
        premiumText: 'Upgrade to premium to access this challenge after September 7th, 2021, at 5:00 PM EST',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRx0ZOeUgBvAtVePHCgKVOzJ0WpXtuHZDUSw&usqp=CAU",
        count: "577",
        starRating: 0,
        link: "https://www.google.com",
        circleColor: ['black', 'white'],
        ropeLB: ['2 LB', '1/2 LB'],
        dailyChallenges: [
            {
                id: '0',
                dayCount: 'DAY 1',
                name: 'Slow & Steady Challenge',
                minutes: '11',
            },
            {
                id: '1',
                dayCount: 'DAY 2',
                name: 'Slow & Steady Challenge',
                minutes: '13',
            },
            {
                id: '2',
                dayCount: 'DAY 3',
                name: 'Slow & Steady Challenge',
                minutes: '15',
            },
            {
                id: '3',
                dayCount: 'DAY 4',
                name: 'Slow & Steady Challenge',
                minutes: '17',
            },
        ],
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                    {
                        id: "2",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif',
            },
        ],
    },
    {
        id: "7",
        title: "Jump Into Summer Challenge",
        overview: 'Ready to say goodbye to the boring cardio? Burn calories fast (and have fun doing it) with our 14 days Have a Blast Challenge full of body weight + jump rope workouts designed to keep you motivated from start to finish.',
        premiumText: 'Upgrade to premium to access this challenge after September 7th, 2021, at 5:00 PM EST',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRx0ZOeUgBvAtVePHCgKVOzJ0WpXtuHZDUSw&usqp=CAU",
        count: "7,577",
        starRating: 0,
        link: "https://www.google.com",
        circleColor: ['black', 'grey', 'white', 'olivedrab'],
        ropeLB: ['2 LB', '1 LB', '1/2 LB', '1/4 LB'],
        dailyChallenges: [
            {
                id: '0',
                dayCount: 'DAY 1',
                name: 'Jump Into Summer Challenge',
                minutes: '11',
            },
            {
                id: '1',
                dayCount: 'DAY 2',
                name: 'Jump Into Summer Challenge',
                minutes: '13',
            },
            {
                id: '2',
                dayCount: 'DAY 3',
                name: 'Jump Into Summer Challenge',
                minutes: '15',
            },
            {
                id: '3',
                dayCount: 'DAY 4',
                name: 'Jump Into Summer Challenge',
                minutes: '17',
            },
        ],
        previewData: [
            {
                id: "1",
                color: "olivedrab",
                block_name: "Block A",
                data: [
                    {
                        id: "1",
                        workout_time: "25s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "15s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
            {
                id: "2",
                color: "white",
                block_name: "Block B",
                data: [
                    {
                        id: "1",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
            {
                id: "3",
                color: "grey",
                block_name: "Block C",
                data: [
                    {
                        id: "1",
                        workout_time: "25s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
                    },
                    {
                        id: "2",
                        workout_time: "20s basic jump",
                        rest_time: "10s of rest",
                        url: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
                    },
                ]
            },
        ],
        warmUpData: [
            {
                id: '1',
                title: 'Get Ready',
                subtitle: 'NEXT UP',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '2',
                title: 'Basic Jump',
                subtitle: '',
                time: '25',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '3',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '4',
                title: 'Bodyweight Squats',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_arms_up,
                background: FSColors.yelloIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '5',
                title: 'Rest',
                subtitle: '',
                time: '15',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
            {
                id: '6',
                title: 'Basic Jump',
                subtitle: '',
                time: '20',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://media0.giphy.com/media/26BRq9PYFLeJl3WLu/giphy.gif',
            },
            {
                id: '7',
                title: 'Rest',
                subtitle: '',
                time: '10',
                icon: AppImages.ic_clock,
                background: FSColors.blueIcon,
                gif: 'https://c.tenor.com/JnEDDPOP564AAAAM/rest-charlie-brown.gif/max_1200/a93c82108677535.5fc3684e78f67.gif',
            },
        ],
    },
]
